eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/

spring:
  zipkin:
    baseUrl: http://192.168.99.100:9411/
  sleuth:
  #  enabled: true
    sampler:
      percentage: 1.0
      probability: 1.0
