eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    baseUrl: http://${DOCKER_HOST:192.168.99.100}:9411/
  sleuth:
    sampler:
      probability: 1.0
